# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  autocli = {
    pname = "autocli";
    version = "v0.3.8";
    src = fetchFromGitHub {
      owner = "nashsu";
      repo = "AutoCLI";
      rev = "v0.3.8";
      sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };
  };
}
