# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bbg = {
    pname = "bbg";
    version = "20230219";
    src = fetchurl {
      url = "https://github.com/bbg-contributors/bbg/releases/download/20230219/app.asar";
      sha256 = "sha256-Gh8XMnMVehVqd6NNWBmFSrsiyp6nmhWEU+qFASJRq/M=";
    };
  };
}
